import { useEffect, useState } from "react";
import API from "../services/api";

export default function ResearchTrends() {
    const [data, setData] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState("");
    const load = async () => {
        setLoading(true); setError("");
        try { const response = await API.get("/ai/research-trends"); setData(response.data); }
        catch { setError("Research intelligence is temporarily unavailable."); }
        finally { setLoading(false); }
    };
    useEffect(() => { load(); }, []);
    if (loading) return <section className="page-container"><h1>AI Research Intelligence</h1><p>Loading database-derived insights...</p></section>;
    if (error) return <section className="page-container"><h1>AI Research Intelligence</h1><p className="server-error">{error}</p><button type="button" onClick={load}>Retry</button></section>;
    const overview = data?.overview || {};
    return <section className="page-container"><div style={{ marginBottom: "24px" }}><h1>AI Research Intelligence</h1><p style={{ color: "var(--muted)" }}>Explore research trends, collaboration patterns, and insights across the SCNA network.</p></div><div className="dashboard-grid">{[["Researchers", overview.researchers], ["Publications", overview.publications], ["Collaborations", overview.collaborations], ["Research Areas", overview.research_areas]].map(([label, value]) => <div className="card" key={label}><h2>{value ?? 0}</h2><p>{label}</p></div>)}</div><div style={gridStyle}><DataPanel title="Top Research Areas" items={data?.research_trends?.top_interests} /><DataPanel title="Frequent Keywords" items={data?.research_trends?.top_keywords} /><DataPanel title="Emerging Areas" items={data?.research_trends?.emerging_areas} empty="Insufficient historical data to determine a reliable trend." /><DataPanel title="Most Active Researchers" items={data?.research_trends?.active_researchers} /><DataPanel title="Active Institutions" items={data?.research_trends?.active_institutions} /><DataPanel title="Low-Activity Areas" items={data?.research_trends?.low_activity_areas} /><DataPanel title="Connected Researchers" items={data?.collaboration_insights?.connected_researchers} /><DataPanel title="Common Collaboration Areas" items={data?.collaboration_insights?.common_research_areas} /></div><div className="card-surface" style={{ padding: "24px", marginTop: "22px" }}><h2>Publication Activity</h2>{data?.research_trends?.publication_activity?.length ? <SimpleBars items={data.research_trends.publication_activity} /> : <p style={{ color: "var(--muted)" }}>No publication date history is available.</p>}{data?.research_trends?.trend_message && <p style={{ color: "var(--muted)" }}>{data.research_trends.trend_message}</p>}</div><div className="card-surface" style={{ padding: "24px", marginTop: "22px" }}><h2>Collaboration Insights</h2>{data?.collaboration_insights?.potential_opportunities?.length ? data.collaboration_insights.potential_opportunities.map((item) => <div key={item.researchers} style={{ padding: "12px 0", borderBottom: "1px solid var(--border)" }}><strong>{item.researchers}</strong><p style={{ color: "var(--muted)", margin: "6px 0" }}>{item.reason}</p></div>) : <p style={{ color: "var(--muted)" }}>No evidence-based collaboration opportunities are available from the current records.</p>}</div><div className="card-surface" style={{ padding: "24px", marginTop: "22px" }}><h2>Research Network Insights</h2><p>{data?.ai_insight || "AI-generated interpretation is unavailable."}</p>{!data?.ai_available && <small style={{ color: "var(--muted)" }}>Database-derived statistics are shown; AI interpretation is currently unavailable.</small>}</div></section>;
}

function DataPanel({ title, items = [], empty = "No records found." }) { return <div className="card-surface" style={{ padding: "22px" }}><h2>{title}</h2>{items?.length ? <ul style={{ paddingLeft: "20px" }}>{items.map((item) => <li key={`${item.label}-${item.value}`} style={{ margin: "10px 0" }}><strong>{item.label}</strong> — {item.value}</li>)}</ul> : <p style={{ color: "var(--muted)" }}>{empty}</p>}</div>; }
function SimpleBars({ items }) { const max = Math.max(...items.map((item) => item.value), 1); return <div style={{ display: "grid", gap: "10px" }}>{items.map((item) => <div key={item.label}><div style={{ display: "flex", justifyContent: "space-between" }}><span>{item.label}</span><strong>{item.value}</strong></div><div style={{ height: "8px", background: "var(--border)", borderRadius: "999px", marginTop: "5px" }}><div style={{ height: "100%", width: `${item.value / max * 100}%`, background: "var(--accent)", borderRadius: "999px" }} /></div></div>)}</div>; }
const gridStyle = { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(260px,1fr))", gap: "20px", marginTop: "22px" };
