"""add file_original_name for cloudinary uploads

Revision ID: 0b1d6ef195cb
Revises: 47764ae2f2ff
Create Date: 2026-08-20 13:57:23.176288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b1d6ef195cb'
down_revision: Union[str, Sequence[str], None] = '47764ae2f2ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('file_original_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'file_original_name')
    # ### end Alembic commands ###
