"""add conference_id to publications

Revision ID: 27254b92f236
Revises: 94b9c4043482
Create Date: 2026-07-19 13:11:56.789595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27254b92f236'
down_revision: Union[str, Sequence[str], None] = '94b9c4043482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('conference_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'publications', 'conferences', ['conference_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'publications', type_='foreignkey')
    op.drop_column('publications', 'conference_id')
    # ### end Alembic commands ###
