"""add publication type

Revision ID: 3ce27cd35508
Revises: 94b9c4043482
Create Date: 2026-07-19 18:33:03.467452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ce27cd35508'
down_revision: Union[str, Sequence[str], None] = '94b9c4043482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('publication_type', sa.String(length=30), nullable=False, server_default='JOURNAL_PAPER'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publications', 'publication_type')
    # ### end Alembic commands ###
