"""add conference mode and meeting link

Revision ID: 4ca1fd4b1b14
Revises: f594d61d31c9
Create Date: 2026-07-31 16:40:13.279646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca1fd4b1b14'
down_revision: Union[str, Sequence[str], None] = 'f594d61d31c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('conferences', sa.Column('mode', sa.String(length=20), nullable=False, server_default='IN_PERSON'))
    op.add_column('conferences', sa.Column('meeting_link', sa.String(length=500), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conferences', 'meeting_link')
    op.drop_column('conferences', 'mode')
    # ### end Alembic commands ###
