"""add citations

Revision ID: a93b1c72f1cf
Revises: 4ca1fd4b1b14
Create Date: 2026-07-31 17:28:59.527363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a93b1c72f1cf'
down_revision: Union[str, Sequence[str], None] = '4ca1fd4b1b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('cited_title', sa.String(length=500), nullable=False),
    sa.Column('cited_authors', sa.String(length=500), nullable=True),
    sa.Column('cited_year', sa.Integer(), nullable=True),
    sa.Column('cited_source', sa.String(length=300), nullable=True),
    sa.Column('cited_doi', sa.String(length=255), nullable=True),
    sa.Column('cited_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citations_id'), 'citations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citations_id'), table_name='citations')
    op.drop_table('citations')
    # ### end Alembic commands ###
