"""add conference registrations

Revision ID: e5d557576da0
Revises: 3ce27cd35508
Create Date: 2026-07-20 11:41:09.672771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5d557576da0'
down_revision: Union[str, Sequence[str], None] = '3ce27cd35508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conference_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conference_id', sa.Integer(), nullable=False),
    sa.Column('researcher_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('presentation_title', sa.String(length=500), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conference_id'], ['conferences.id'], ),
    sa.ForeignKeyConstraint(['researcher_id'], ['researchers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conference_id', 'researcher_id', name='uq_conference_researcher')
    )
    op.create_index(op.f('ix_conference_registrations_id'), 'conference_registrations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conference_registrations_id'), table_name='conference_registrations')
    op.drop_table('conference_registrations')
    # ### end Alembic commands ###
