import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import api from '../config/api';

const AdminDashboard = () => {
  const [stats, setStats] = useState(null); const [error, setError] = useState('');
  useEffect(() => { api.get('/dashboard/stats').then((res) => setStats(res.data)).catch((err) => setError(err.response?.data?.detail || 'Failed to load dashboard')); }, []);
  const cards = [['Total users', stats?.users_count], ['Active users', stats?.active_users_count], ['Pending role requests', stats?.pending_role_requests_count], ['New users this month', stats?.new_users_this_month], ['Researchers', stats?.researchers_count], ['Publications', stats?.publications_count], ['Citations', stats?.citations_count], ['Collaborations', stats?.collaboration_count], ['New publications this month', stats?.new_publications_this_month], ['New collaborations this month', stats?.new_collaborations_this_month], ['Institutions', stats?.institutions_count]];
  return <div className="container py-4"><div className="d-flex justify-content-between align-items-center mb-4"><div><h3 className="mb-1">System administration</h3><p className="text-muted mb-0">Platform overview, access control, and research activity.</p></div><Link to="/admin/users" className="btn btn-primary">User Management</Link></div>
    {error && <div className="alert alert-danger">{error}</div>}{!stats ? <div className="text-center py-5"><div className="spinner-border" /></div> : <><div className="row g-3 mb-4">{cards.map(([label, value]) => <div className="col-6 col-md-3" key={label}><div className="card h-100 shadow-sm"><div className="card-body"><small className="text-muted">{label}</small><h3 className="mb-0">{value ?? 0}</h3></div></div></div>)}</div><div className="row g-3"><div className="col-md-7"><div className="card"><div className="card-header">Publications by institution</div><ul className="list-group list-group-flush">{stats.publications_by_institution?.length ? stats.publications_by_institution.map((item) => <li className="list-group-item d-flex justify-content-between" key={item.name}>{item.name}<span className="badge bg-primary">{item.count}</span></li>) : <li className="list-group-item text-muted">No publication activity yet.</li>}</ul></div></div><div className="col-md-5"><div className="card"><div className="card-header">Recently joined</div><ul className="list-group list-group-flush">{stats.recent_users?.map((item) => <li className="list-group-item" key={item.id}><strong>{item.name}</strong><br/><small>{item.role.replace('_', ' ')}</small></li>)}</ul></div></div></div></>}</div>;
};
export default AdminDashboard;
