import React, { useContext, useEffect, useState } from 'react';
import api from '../config/api';
import { AuthContext } from '../context/AuthContext';

const message = detail => Array.isArray(detail) ? detail.map(x => x.msg).join('. ') : detail || 'Unable to complete the request';
export default function Citations() {
  const { user } = useContext(AuthContext); const canManage = ['researcher', 'system_admin'].includes(user?.role);
  const [publications, setPublications] = useState([]), [citations, setCitations] = useState([]), [selected, setSelected] = useState(''), [cited, setCited] = useState(''), [reference, setReference] = useState({title:'',authors:'',journal:'',year:'',doi:'',url:''}), [references, setReferences] = useState([]), [error, setError] = useState('');
  const load = async () => { try { const [p,c] = await Promise.all([api.get('/publications/'),api.get('/citations')]);setPublications(p.data);setCitations(c.data)}catch(e){setError(message(e.response?.data?.detail))} };
  useEffect(()=>{load()},[]); useEffect(()=>{if(selected)api.get(`/citations/publications/${selected}/references`).then(r=>setReferences(r.data)).catch(()=>setReferences([]));else setReferences([])},[selected]);
  const addCitation=async e=>{e.preventDefault();try{await api.post('/citations',{citing_publication_id:+selected,cited_publication_id:+cited});setCited('');load()}catch(e){setError(message(e.response?.data?.detail))}};
  const addReference=async e=>{e.preventDefault();try{await api.post(`/citations/publications/${selected}/references`,{...reference,year:reference.year ? +reference.year:null});setReference({title:'',authors:'',journal:'',year:'',doi:'',url:''});setReferences((await api.get(`/citations/publications/${selected}/references`)).data)}catch(e){setError(message(e.response?.data?.detail))}};
  return <div className="container py-5"><h2>Citations & References</h2>{error&&<div className="alert alert-danger">{error}</div>}<div className="row"><div className="col-md-6"><div className="card"><div className="card-body"><h5>{canManage?'Manage a publication':'Institution citation information'}</h5>{!canManage&&<p className="text-muted">Read-only results are limited to publications from your institution.</p>}<select className="form-select mb-3" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose a publication</option>{publications.map(p=><option key={p.id} value={p.id}>{p.title} ({p.citation_count} citations)</option>)}</select>{selected&&canManage&&<><form onSubmit={addCitation}><select className="form-select mb-2" value={cited} onChange={e=>setCited(e.target.value)} required><option value="">Publication being cited</option>{publications.filter(p=>String(p.id)!==String(selected)).map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select><button className="btn btn-primary">Link citation</button></form><hr/><form onSubmit={addReference}><input className="form-control mb-2" placeholder="Reference title" value={reference.title} onChange={e=>setReference({...reference,title:e.target.value})} required/><input className="form-control mb-2" placeholder="Authors" value={reference.authors} onChange={e=>setReference({...reference,authors:e.target.value})}/><input className="form-control mb-2" placeholder="Journal" value={reference.journal} onChange={e=>setReference({...reference,journal:e.target.value})}/><input className="form-control mb-2" placeholder="Year" type="number" value={reference.year} onChange={e=>setReference({...reference,year:e.target.value})}/><input className="form-control mb-2" placeholder="DOI" value={reference.doi} onChange={e=>setReference({...reference,doi:e.target.value})}/><input className="form-control mb-2" placeholder="URL" value={reference.url} onChange={e=>setReference({...reference,url:e.target.value})}/><button className="btn btn-outline-primary">Add reference</button></form></>}</div></div></div><div className="col-md-6"><div className="card mb-3"><div className="card-header">Citation links</div><ul className="list-group list-group-flush">{citations.map(c=><li className="list-group-item" key={c.id}>{c.citing_title} <strong>cites</strong> {c.cited_title}</li>)}{!citations.length&&<li className="list-group-item text-muted">No citations yet.</li>}</ul></div><div className="card"><div className="card-header">Reference list</div><ul className="list-group list-group-flush">{references.map(r=><li className="list-group-item" key={r.id}><strong>{r.title}</strong><div className="small">{r.authors} {r.journal&&`· ${r.journal}`} {r.year&&`(${r.year})`} {r.doi&&`· DOI: ${r.doi}`}</div></li>)}{selected&&!references.length&&<li className="list-group-item text-muted">No references for this publication.</li>}</ul></div></div></div></div>;
}
