import React, { useContext, useEffect, useState } from 'react';
import api from '../config/api';
import { AuthContext } from '../context/AuthContext';

const emptyProject = { title: '', description: '', start_date: '', end_date: '', status: 'planning' };

export default function CollaborationHub() {
  const { user } = useContext(AuthContext);
  const canManageProjects = ['researcher', 'system_admin'].includes(user?.role);
  const [projects, setProjects] = useState([]), [collaborations, setCollaborations] = useState([]), [form, setForm] = useState(emptyProject), [editing, setEditing] = useState(null), [error, setError] = useState('');
  const load = async () => { try { const [p, c] = await Promise.all([api.get('/collaborations/projects'), api.get('/collaborations')]); setProjects(p.data); setCollaborations(c.data); } catch (e) { setError(e.response?.data?.detail || 'Unable to load collaboration data'); } };
  useEffect(() => { load(); }, []);
  const save = async e => { e.preventDefault(); try { const data = { ...form, start_date: form.start_date || null, end_date: form.end_date || null }; editing ? await api.put(`/collaborations/projects/${editing}`, data) : await api.post('/collaborations/projects', data); setForm(emptyProject); setEditing(null); load(); } catch (e) { setError(e.response?.data?.detail || 'Unable to save project'); } };
  const edit = p => { setEditing(p.id); setForm({ title:p.title, description:p.description || '', start_date:p.start_date || '', end_date:p.end_date || '', status:p.status }); };
  const remove = async id => { if (!window.confirm('Delete this project?')) return; try { await api.delete(`/collaborations/projects/${id}`); load(); } catch (e) { setError(e.response?.data?.detail || 'Unable to delete project'); } };
  const updateCollaboration = async (id, status) => { try { await api.put(`/collaborations/${id}`, { status }); load(); } catch (e) { setError(e.response?.data?.detail || 'Unable to update request'); } };
  return <div className="container py-5"><div className="d-flex justify-content-between align-items-center"><h2>Collaboration Hub</h2><span className="badge bg-primary">{projects.length} projects</span></div>{error && <div className="alert alert-danger mt-3">{error}</div>}
    <div className="row mt-3"><div className="col-lg-7"><div className="card shadow-sm"><div className="card-header"><strong>Active Projects</strong></div><div className="list-group list-group-flush">{projects.length ? projects.map(p => <div className="list-group-item" key={p.id}><div className="d-flex justify-content-between"><div><strong>{p.title}</strong><div className="small text-muted">{p.status.replace('_', ' ')} · {p.member_count} members</div><div>{p.description}</div></div><div><button className="btn btn-sm btn-outline-primary me-1" onClick={() => edit(p)}>Edit</button><button className="btn btn-sm btn-outline-danger" onClick={() => remove(p.id)}>Delete</button></div></div></div>) : <div className="list-group-item text-muted">No projects yet.</div>}</div></div>
      <div className="card shadow-sm mt-4"><div className="card-header"><strong>My Collaborations / Requests</strong></div><div className="list-group list-group-flush">{collaborations.length ? collaborations.map(c => <div key={c.id} className="list-group-item d-flex justify-content-between"><span>{c.researcher1_name} ↔ {c.researcher2_name}<small className="d-block text-muted">{c.collaboration_type} · {c.status}</small></span>{c.status === 'pending' && <span><button className="btn btn-sm btn-success me-1" onClick={() => updateCollaboration(c.id, 'active')}>Accept</button><button className="btn btn-sm btn-outline-danger" onClick={() => updateCollaboration(c.id, 'rejected')}>Decline</button></span>}</div>) : <div className="list-group-item text-muted">No collaboration requests.</div>}</div></div></div>
      <div className="col-lg-5">{canManageProjects ? <div className="card shadow-sm"><div className="card-body"><h5>{editing ? 'Edit Project' : 'Create Project'}</h5><form onSubmit={save}><input className="form-control mb-2" placeholder="Project title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/><textarea className="form-control mb-2" placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><div className="row"><div className="col"><input type="date" className="form-control mb-2" value={form.start_date} onChange={e=>setForm({...form,start_date:e.target.value})}/></div><div className="col"><input type="date" className="form-control mb-2" value={form.end_date} onChange={e=>setForm({...form,end_date:e.target.value})}/></div></div><select className="form-select mb-3" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="planning">Planning</option><option value="active">Active</option><option value="on_hold">On hold</option><option value="completed">Completed</option></select><button className="btn btn-primary">{editing ? 'Save changes' : 'Create project'}</button>{editing && <button type="button" className="btn btn-link" onClick={()=>{setEditing(null);setForm(emptyProject)}}>Cancel</button>}</form></div></div> : <div className="alert alert-info">You can view collaboration information for your institution.</div>}</div></div></div>;
}
